version: '3'
services:
  webserver:
    build: 
      context: ..
      dockerfile: .docker/Dockerfile
    volumes:
      - ..:/usr/src/app
    image: djangotest
    ports:
      - "3000:3000"
    links:
      - db_djangotest
    environment:
      DB_HOST: db_djangotest
      DB_DATABASE: djangotest
      DB_USERNAME: user
      DB_PASSWORD: root
  db_djangotest:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: djangotest
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root